blank_issues_enabled: false
contact_links:
  - name: Contribution Guidelines
    url: https://github.com/Swapnil-Dhamal/EventHive/blob/main/.github/CONTRIBUTING.md
    about: Please read the contribution guidelines before creating an issue.
